---
title: "Articles: Tables & Figures"
format:
  html:
    toc: true
    toc-expand: 2
    toc-location: left
    number-sections: true
    self-contained: true
    code-fold: true
    output-file: "analisis"
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
  message: false
  echo: false
---

# Project Setup

```{r}
#| label:  setup

source('https://inkaverse.com/setup.r')

cat("Project: ", getwd())
cat("CPU cores available: ", parallel::detectCores())
RhpcBLASctl::blas_set_num_threads(parallel::detectCores()*0.8)
session_info()
```

# Refencias

> https://cran.r-project.org/web/packages/cowplot/index.html

# Figuras en R


```{r}
# base R
p1 <- function() {
  boxplot(mpg ~ cyl, xlab = "cyl", ylab = "mpg", data = mtcars)
}

# ggplot2
library(ggplot2)
p2 <- ggplot(data = mtcars, aes(factor(cyl), mpg)) + geom_boxplot()

# lattice
library(lattice)
p3 <- bwplot(~mpg | cyl, data = mtcars)

# elementary grid graphics objects
library(grid)
p4 <- circleGrob(r = 0.3, gp = gpar(fill = "skyblue"))


# combine all into one plot

plot <- list(p1, p2, p3, p4) %>% 
  plot_grid(plotlist = .
          , rel_heights = c(1, 1)
          , labels = "auto"
          , nrow = 2
          )

plot %>% ggsave2(plot = .
                 , filename = "Figure-01.jpg"
                 , units = "cm"
                 , width = 20
                 , height = 20
                 , )
```

# Figuras importadas

## Importar

```{r}
plot01 <- image_read("figure1.png") %>% grid::rasterGrob()
plot02 <- image_read("figure2.jpg") %>% grid::rasterGrob()
plot03 <- image_read("figure3.png") %>% grid::rasterGrob()
```

## Grid plots

```{r}
top <- list(plot01, plot02) %>% 
  plot_grid(plotlist = ., labels = "auto")

plot <- list(top, plot03) %>% 
  plot_grid(plotlist = .
            , nrow = 2
            , labels = c("", "c")
            )

plot

plot %>% 
  ggsave2(filename = "grid.jpg"
          , plot = .
          , width = 30
          , height = 20
          , units = "cm"
          )
```
